# Usa una imagen base de Python

FROM python:3.12.4

# Establece el directorio de trabajo

WORKDIR /API_model_tryout

# Copia los archivos de requisitos e instálalos

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del código de la aplicación

COPY . .

# Exponer el puerto en el que correrá la aplicación

EXPOSE 8000

# Comando para ejecutar la aplicación

CMD ["uvicorn", "app_model:app", "--host", "0.0.0.0", "--port", "8000"]